M48
; DRILL file {KiCad (6.0.5-0)} date Friday, 30 September 2022 at 17:34:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-30T17:34:11+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.762
%
G90
G05
T1
X-10.064Y9.928
X-10.064Y-8.072
X5.936Y9.928
X5.936Y-8.072
T0
M30
