site_name: ModelOLED
repo_url: https://github.com/EugenePY/model-oled-pb
nav:
    - Index: zh/index.md
    - Features: zh/features.md
    - Flashing Firmware: zh/firmware_update.md
    - Update Graphics: zh/update_graphics.md
    - VIA: zh/via.md

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - glightbox
  - search
  - alternate-link

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline

extra_css:
  - styles/extra.css

extra:
  alternate:
    - name: 中文
      link: /zh/
      lang: zh-TW
    - name: English
      link: /en/ 
      lang: en

