site_name: ModelOLED
repo_url: https://github.com/EugenePY/model-oled-pb
nav:
    - 主要功能: features.md
    - Flashing韌體: firmware_update.md
    - OLED-UTILS: oled_util_guide.md
    - 更新圖片: update_graphics.md
    - VIA: via.md

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline

extra_css:
  - styles/extra.css
